spring.application.name=airline-management
spring.datasource.url=jdbc:mysql://localhost:3306/airplane_db
spring.datasource.username=root
spring.datasource.password=kichu
# The password was recently changed to kichu from admin so remember it.

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect      --> commented it because spring boot automatically detects it